config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'dashboards/student'

  get 'dashboards/company'

  get 'dashboards/academico'

  post 'dashboards/region_city'

  resources :publications do
    resources :postulations
  end

  devise_for :companies, path: 'companies', controllers: {
    registrations: 'companies/registrations'
  }

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'dashboards#company'
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :company
  belongs_to :area
  belongs_to :type

  has_many :interest_publications, dependent: :destroy
  has_many :interests, through: :interest_publications

  has_many :postulations, dependent: :destroy

  validates_presence_of :titulo, :problema, :description, :premios, message: 'no puede estar en blanco'

  # validate :validates_fecha
  #
  # def validates_fecha
  #   if limite.to_datetime < Date.current.to_s
  #     errors.add(:message, "la fecha #{limite} no puede ser menor a la fecha actual")
  #   end
  # end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  load_and_authorize_resource

  # GET /publications
  # GET /publications.json
  def index
    if company_signed_in?
      @publications = Publication.includes(:type, :area, :company).where(company_id: current_company.id).page(params[:page]).per(6)
    else
      @publications = Publication.includes(:type, :area, :company).order('created_at DESC').page(params[:page]).per(6)
    end
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.company_id = current_company.id
    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def postular
    @postulacion = Application.new()
    @postulacion.user_id = current_user.id
    @postulacion.publication_id = params[:id]
    @postulacion.contenido = params[:contenido]
    respond_to do |format|
      if @postulacion.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publication_params
      params.require(:publication).permit(:titulo, :problema, :limite, :description, :premios, :company_id, :area_id, :type_id, :page)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_for(publication) do |f| %>
<% if publication.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(publication.errors.count, "error") %>
    prohibited this publication from being saved:</h2>

  <ul>
    <% publication.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="row">
  <div class="col-lg-12">
    <div class="form-group">
      <%= f.label :titulo, class: "col-sm-4 col-sm-4 control-label" %>
      <%= f.text_field :titulo, autofocus: true, class: "form-control"  %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      <%= f.label :limite, class: "col-sm-4 col-sm-4 control-label" %>
      <%= f.text_field :limite, class: "form-control", id: 'datetimepicker1'%>
    </div>
    <div class="form-group">
      <%= f.label 'Area', class: "col-sm-4 col-sm-4 control-label" %><br/>
      <%= collection_select :publication, :area_id, Area.all, :id, :nombre, {prompt: true}, {class: "form-control selectpicker", "data-live-search" => "true"} %>
    </div>
  </div>
  <div class="col-lg-6">
    <div class="form-group">
      <%= f.label 'Tipo de publicacion', class: "col-sm-4 col-sm-4 control-label" %><br/>
      <%= collection_select :publication, :type_id, Type.all, :id, :nombre, {prompt: true}, {class: "form-control selectpicker", "data-live-search" => "true"} %>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-lg-12">
    <div class="form-group">
      <%= f.label :problema, class: "col-sm-4 col-sm-4 control-label"  %>
      <%= f.text_area :problema, class: "form-control", rows: 4, placeholder: "..." %>
    </div>

    <div class="form-group">
      <%= f.label 'Descripción', class: "col-sm-4 col-sm-4 control-label"  %>
      <%= f.text_area :description, class: "form-control", rows: 4, placeholder: "..." %>
    </div>

    <div class="form-group">
      <%= f.label :premios, class: "col-sm-4 col-sm-4 control-label"  %>
      <%= f.text_area :premios, class: "form-control", rows: 4, placeholder: "..." %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="actions">
      <%= f.submit class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>
<% end %>

app/views/publications/edit.html.erb
<div class="row mt">
  <div class="col-lg-12">
    <div class="form-panel">
      <h3 class="mb">
        <i class="fa fa-angle-right"></i>editar Publicación
      </h3>

      <%= render 'form', publication: @publication %>

      <%= link_to 'Show', @publication %>
      |
      <%= link_to 'Back', publications_path %>
    </div>
  </div>
</div>

app/views/publications/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-11 titulo">
    <h4>
      <i class="fa fa-angle-right"></i>Publicaciones</h4>
  </div>
</div>
<% @publications.each do |publication| %>
<div class="row mt margin-minus">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="form-panel">
      <div class="row">
        <div class="col-lg-7 col-lg-offset-1">
          <h4><i class="fa fa-angle-right"></i><%= publication.titulo %></h4>
          <p class="margin-minus-minus">
            <span class="label label-primary"><%= publication.type.nombre %></span>
            <span class="label label-info"><%= publication.area.nombre %></span>
            <%= publication.limite.strftime("%d-%m-%Y") %>
          </p>
          <p>
            <%= publication.problema %>
          </p>
          <%= link_to 'Ver Publicacion', publication, class: "btn btn-success btn-xs" %>
        </div>
        <div class="col-lg-3">
          <h4><%= publication.company.razon %></h4>
          <%= image_tag(current_entity.avatar.url, width: 100)%>
        </div>
        <!--
  <%= link_to 'Edit', edit_publication_path(publication) %>
  <%= link_to 'Destroy', publication, method: :delete, data: { confirm: 'Are you sure?' } %> -->
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="row">
  <div class="col-lg-10 col-lg-offset-1 centrado">
    <%= paginate(@publications) %>
  </div>
</div>

app/views/publications/new.html.erb
<div class="row mt">
  <div class="col-lg-12">
    <div class="form-panel">
      <h3 class="mb">
        <i class="fa fa-angle-right"></i>Nueva Publicación
      </h3>

      <%= render 'form', publication: @publication %>

    </div>
  </div>
</div>

app/views/publications/show.html.erb
<div class="row">
  <div class="col-lg-11 titulo">
    <h3>
      <i class="fa fa-arrow-right"></i>
      <%= @publication.titulo %></h3>
    <p>creado el
      <%= @publication.created_at.strftime("%d-%m-%Y") %></p>
    <p class="margin-minus-minus">
      <span class="label label-primary"><%= @publication.type.nombre %></span>
      <span class="label label-info"><%= @publication.area.nombre %></span>
    </p>
  </div>
</div>
<div class="row mt margin-minus">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="form-panel show">
      <h5>
        <i class="fa fa-building"></i>
        ¿Qué nos pasa?</h5>
      <p>
        <%= @publication.problema %>
      </p>

      <h5>
        <i class="fa fa-graduation-cap"></i>
        Que deberas hacer</h5>
      <p>
        <%= @publication.description %>
      </p>

      <h5>
        <i class="fa fa-trophy"></i>
        Los premios</h5>
      <p>
        <%= @publication.premios %>
      </p>

      <p>
        <strong>Limite:</strong>
        <%= @publication.limite %>
      </p>
      <hr>
      <h3>Empresa
        <%= @publication.company.razon %></h3>

      <p><%= @publication.company.resumen %></p>

    </div>
  </div>
</div>
<% if can? :manage, Publication %>
<div class="row mt margin-minus">
  <div class="col-lg-10 col-lg-offset-1">
      <div class="form-panel">
        <h4><i class="fa fa-angle-right"></i> Acciones</h4>
        <%= link_to 'Editar', edit_publication_path(@publication), class: "btn btn-default btn-lg" %>
        <%= link_to 'Postulaciones', publication_postulations_path(@publication), class: "btn btn-info btn-lg" %>
        <%= link_to 'Eliminar', @publication, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg" %>
      </div>
  </div>
</div>
<% end %>
<% if can? :create, Postulation %>
<div class="row mt margin-minus">
  <div class="col-lg-10 col-lg-offset-1">
      <div class="form-panel">
        <h4><i class="fa fa-angle-right"></i> Acciones</h4>
        <button class="btn btn-default btn-lg" id="postulando" data-toggle="modal" data-target="#myModal">Postular</button>
        <button type="button" name="button" class="btn btn-info btn-lg">Enviar a un amigo</button>
      </div>
  </div>
</div>
<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Postular</h4>
      </div>
      <div class="modal-body">
        <%= form_for([@publication, @publication.postulations.new], remote: true) do |f| %>
        <%= f.text_area :contenido, rows:"8", cols: "80", class: "form-control" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit 'Enviar Postulacion', class: "btn btn-primary", id: "btnPostulacion" %>
        <% end %>
      </div>
    </div>
  </div>
</div>