config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'dashboards/student'

  get 'dashboards/company'

  get 'dashboards/academico'

  post 'dashboards/region_city'

  resources :publications do
    resources :postulations
  end

  devise_for :companies, path: 'companies', controllers: {
    registrations: 'companies/registrations'
  }

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'dashboards#company'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user
    when User
      can :read, Publication
      can [:create, :update], Postulation
      can :manage, User
    when Company
      can :manage, Publication
      can :read, Postulation
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :publications
  
end

app/models/career.rb
class Career < ApplicationRecord
  has_many :user_careers
  has_many :users, through: :user_careers
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :users, dependent: :destroy
  has_many :companies, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :region_id
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :publications, dependent: :destroy
belongs_to :city

validates_presence_of :email, :rut, message: 'no puede estar en blanco'
validates_uniqueness_of :email, :rut, message: "esta en uso"
validates_format_of :rut,
                    :with => /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i,
                    :message => "no válido."
validates_email_format_of :email, :message => 'no tiene formato de email'

	def self.recreate_avatar
		Company.find_each do |m|
			begin
				m.avatar.recreate_versions! if m.avatar?
			rescue => e
				puts  "ERROR: #{m.id} -> #{e.to_s}"
			end
		end
	end

end

app/models/disc_profile.rb
class DiscProfile < ApplicationRecord
  belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests

  has_many :interest_publications
  has_many :publications, through: :interest_publications

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :postulation
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  has_many :messages, dependent: :destroy

  validates_presence_of :contenido, message: 'no puede estar en blanco'

end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :company
  belongs_to :area
  belongs_to :type

  has_many :interest_publications, dependent: :destroy
  has_many :interests, through: :interest_publications

  has_many :postulations, dependent: :destroy

  validates_presence_of :titulo, :problema, :description, :premios, message: 'no puede estar en blanco'

  # validate :validates_fecha
  #
  # def validates_fecha
  #   if limite.to_datetime < Date.current.to_s
  #     errors.add(:message, "la fecha #{limite} no puede ser menor a la fecha actual")
  #   end
  # end

end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :publications, dependent: :destroy
end

app/models/university.rb
class University < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :region_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :user_careers
  has_many :careers, through: :user_careers

  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :postulations, dependent: :destroy

  belongs_to :city
  has_one :disc_profile
  belongs_to :university, optional: true

  validates_presence_of :email, :encrypted_password, :rut, :nombre, :paterno, :materno, :genero, message: "no puede estar en blanco"
  validates_uniqueness_of :email, :rut, message: "esta en uso"
  validates_format_of :rut,
                      :with => /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i,
                      :message => "no válido."
  validates_email_format_of :email, :message => 'no tiene formato de email'

  def self.recreate_avatar
    User.find_each do |m|
      begin
        m.avatar.recreate_versions! if m.avatar?
      rescue => e
        puts  "ERROR: #{m.id} -> #{e.to_s}"
      end
    end
  end

end

app/models/user_career.rb
class UserCareer < ApplicationRecord
  belongs_to :user
  belongs_to :career
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :interest
  belongs_to :user
end

app/controllers/postulations_controller.rb
class PostulationsController < ApplicationController
  load_and_authorize_resource

  # GET /applications
  # GET /applications.json
  def index
    publication = Publication.find(params[:publication_id])
    @postulations = publication.postulations.includes(:user).order('created_at DESC')
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @postulation = Postulation.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @postulation = Postulation.new(postulation_params)
    @postulation.publication_id = params[:publication_id]
    @postulation.user_id = current_user.id

    respond_to do |format|
      if @postulation.save
        format.html { redirect_to @postulation, notice: 'Application was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @postulation.update(postulation_params)
        format.html { redirect_to @postulation, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @postulation }
      else
        format.html { render :edit }
        format.json { render json: @postulation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @postulation.destroy
    respond_to do |format|
      format.html { redirect_to postulations_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_postulation
      @postulation = Postulation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def postulation_params
      params.require(:postulation).permit(:user_id, :publication_id, :contenido)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/postulations/_form.html.erb
<%= form_for([@publication, @publication.postulations.build]) do |f| %>
  <% if postulation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(postulation.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% postulation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :publication_id %>
    <%= f.text_field :publication_id %>
  </div>

  <div class="field">
    <%= f.label :contenido %>
    <%= f.text_area :contenido %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/postulations/create.js.erb
swal("Postulacion", "Tu postulacion a sido enviada!", "success");

app/views/postulations/edit.html.erb
<h1>Editing postulation</h1>

<%= render 'form', postulation: @postulation %>

<%= link_to 'Show', @postulation %> |
<%= link_to 'Back', postulations_path %>

app/views/postulations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-11 titulo">
    <h4>
      <i class="fa fa-angle-right"></i>Postulaciones</h4>
  </div>
</div>
<% @postulations.each do |postulation| %>
<div class="row mt margin-minus">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="form-panel">
      <div class="row">
        <div class="col-lg-7 col-lg-offset-1">
          <h4><%= postulation.user.nombre %> <%= postulation.user.paterno %> <%= postulation.user.materno %></h4>
          <p>
            <%= postulation.contenido %>
          </p>
           <%= link_to 'Ver postulacion', [postulation.publication, postulation], class: "btn btn-success btn-xs" %>
        <!-- <%= link_to 'Edit', edit_publication_postulation_path(postulation.publication, postulation) %>
          <%= link_to 'Destroy', [postulation.publication, postulation], method: :delete, data: { confirm: 'Are you sure?' } %> -->
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

<br>

<!-- # <%= link_to 'New Application', new_publication_postulation_path %> -->

app/views/postulations/new.html.erb
<h1>New postulation</h1>

<%= render 'form', postulation: @postulation %>

<%= link_to 'Back', postulations_path %>

app/views/postulations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row mt">
  <div class="col-lg-10 col-lg-offset-1">
    <div class="form-panel">
      <div class="row">
        <div class="col-lg-9 col-lg-offset-1">
          <h2>
            <%= @postulation.user.nombre %> <%= @postulation.user.paterno %> <%= @postulation.user.materno %>
          </h2>
          <ul>
            <li><%= @postulation.user.genero %></li>
            <li><%= @postulation.user.university.nombre %></li>
            <li><%= @postulation.user.careers %></li>
          </ul>
          <h4>
            <i class="fa fa-arrow-right"></i>
            Postulacion</h4>
          <p>
            <%= @postulation.contenido %>
          </p>
      </div>
    </div>
  </div>
</div>
</div>
<%= link_to 'Edit', edit_publication_postulation_path(@postulation) %>
|
<%= link_to 'Back', publication_postulations_path %>