config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'dashboards/student'

  get 'dashboards/company'

  get 'dashboards/academico'

  post 'dashboards/region_city'

  resources :publications do
    resources :postulations
  end

  devise_for :companies, path: 'companies', controllers: {
    registrations: 'companies/registrations'
  }

  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations'
      }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'dashboards#company'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user
    when User
      can :read, Publication
      can [:create, :update], Postulation
      can :manage, User
    when Company
      can :manage, Publication
      can :read, Postulation
    end
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :publications
  
end

app/models/career.rb
class Career < ApplicationRecord
  has_many :user_careers
  has_many :users, through: :user_careers
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :region
  has_many :users, dependent: :destroy
  has_many :companies, dependent: :destroy
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :region_id
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :publications, dependent: :destroy
belongs_to :city

validates_presence_of :email, :rut, message: 'no puede estar en blanco'
validates_uniqueness_of :email, :rut, message: "esta en uso"
validates_format_of :rut,
                    :with => /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i,
                    :message => "no válido."
validates_email_format_of :email, :message => 'no tiene formato de email'

	def self.recreate_avatar
		Company.find_each do |m|
			begin
				m.avatar.recreate_versions! if m.avatar?
			rescue => e
				puts  "ERROR: #{m.id} -> #{e.to_s}"
			end
		end
	end

end

app/models/disc_profile.rb
class DiscProfile < ApplicationRecord
  belongs_to :user
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :user_interests
  has_many :users, through: :user_interests

  has_many :interest_publications
  has_many :publications, through: :interest_publications

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :postulation
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :user
  belongs_to :publication

  has_many :messages, dependent: :destroy

  validates_presence_of :contenido, message: 'no puede estar en blanco'

end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :company
  belongs_to :area
  belongs_to :type

  has_many :interest_publications, dependent: :destroy
  has_many :interests, through: :interest_publications

  has_many :postulations, dependent: :destroy

  validates_presence_of :titulo, :problema, :description, :premios, message: 'no puede estar en blanco'

  # validate :validates_fecha
  #
  # def validates_fecha
  #   if limite.to_datetime < Date.current.to_s
  #     errors.add(:message, "la fecha #{limite} no puede ser menor a la fecha actual")
  #   end
  # end

end

app/models/region.rb
class Region < ApplicationRecord
  has_many :cities, dependent: :destroy
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :publications, dependent: :destroy
end

app/models/university.rb
class University < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :region_id
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :user_careers
  has_many :careers, through: :user_careers

  has_many :user_interests
  has_many :interests, through: :user_interests
  has_many :postulations, dependent: :destroy

  belongs_to :city
  has_one :disc_profile
  belongs_to :university, optional: true

  validates_presence_of :email, :encrypted_password, :rut, :nombre, :paterno, :materno, :genero, message: "no puede estar en blanco"
  validates_uniqueness_of :email, :rut, message: "esta en uso"
  validates_format_of :rut,
                      :with => /\A(\d{1,3})\.(\d{1,3})\.(\d{1,3})\-(k|\d{1})\Z/i,
                      :message => "no válido."
  validates_email_format_of :email, :message => 'no tiene formato de email'

  def self.recreate_avatar
    User.find_each do |m|
      begin
        m.avatar.recreate_versions! if m.avatar?
      rescue => e
        puts  "ERROR: #{m.id} -> #{e.to_s}"
      end
    end
  end

end

app/models/user_career.rb
class UserCareer < ApplicationRecord
  belongs_to :user
  belongs_to :career
end

app/models/user_interest.rb
class UserInterest < ApplicationRecord
  belongs_to :interest
  belongs_to :user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/layouts/company.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enode - Empresas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma On-line para vinculaciones de estudiantes con empresas que buscan estudiantes para practicas o resolver problemas.">
    <meta name="keyword" content="Vinculaciones, Estudiante, Empresas, Practicas, Proyectos, Problemas, Postulaciones">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <section id="container" >
    <%= render "shared/navbarCompany"%>
    <%= render "shared/sidebarCompany"%>
      <section id="main-content">
          <section class="wrapper site-min-height">
              <div class="row">
                
              <% if notice.present? %>
              <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= notice %>
              </div>
              <% end %>
              <% if alert.present? %>
              <div class="alert alert-warning alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <%= alert %>
              </div>
              <% end %>


                <%= yield %>



               </div>
          </section>
      </section>
  <%= render "shared/footer"%>

  </section>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enode - Empresas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma On-line para vinculaciones de estudiantes con empresas que buscan estudiantes para practicas o resolver problemas.">
    <meta name="keyword" content="Vinculaciones, Estudiante, Empresas, Practicas, Proyectos, Problemas, Postulaciones">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="login-page">
      <div class="container">
        <% if notice.present? %>
        <div class="alert alert-success alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= notice %>
        </div>
        <% end %>
        <% if alert.present? %>
        <div class="alert alert-warning alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= alert %>
        </div>
        <% end %>
        
        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enode - Estudiantes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Plataforma On-line para vinculaciones de estudiantes con empresas que buscan estudiantes para practicas o resolver problemas.">
    <meta name="keyword" content="Vinculaciones, Estudiante, Empresas, Practicas, Proyectos, Problemas, Postulaciones">
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

  <section id="container" >
    <%= render "shared/navbarUser"%>
    <%= render "shared/sidebarUser"%>
      <section id="main-content">
          <section class="wrapper site-min-height">
              <div class="row">
                <% if notice.present? %>
                <div class="alert alert-success alert-dismissable">
    						  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    						  <%= notice %>
    						</div>
                <% end %>
                <% if alert.present? %>
                <div class="alert alert-warning alert-dismissable">
    						  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    						  <%= alert %>
    						</div>
                <% end %>

                <%= yield %>



               </div>
          </section>
      </section>
  <%= render "shared/footer"%>

  </section>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
  <script>
  $(document).on('turbolinks:load', function() {
      $("#btnPostulacion").on('click', function(e){
        e.preventDefault();
        $('#new_postulation').submit();
        e.stopImmediatePropagation();
      });
  });
  </script>
  </body>
</html>

app/views/shared/_footer.html.erb
     <!--footer start-->
      <footer class="site-footer">
          <div class="text-center">
              2017 - Vincul@ndo
              <a href="index.html#" class="go-top">
                  <i class="fa fa-angle-up"></i>
              </a>
          </div>
      </footer>
      <!--footer end-->

app/views/shared/_navbarCompany.html.erb
<header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips"></div>
              </div>
            <!--logo start-->
            <a href="<%= root_path %>" class="logo"><b>Enode</b></a>
            <!--logo end-->

            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><%= link_to "Cerrar Sesión", destroy_company_session_path, method: :delete, class:"logout" %></li>
            	</ul>
            </div>
        </header>

app/views/shared/_navbarUser.html.erb
<header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div class="fa fa-bars tooltips"></div>
              </div>
            <!--logo start-->
            <a href="<%= root_path %>" class="logo"><b>Enode</b></a>
            <!--logo end-->

            <div class="top-menu">
            	<ul class="nav pull-right top-menu">
                    <li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:"logout" %></li>
            	</ul>
            </div>
        </header>

app/views/shared/_sidebar.html.erb
    <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
              
              	  <p class="centered"><a href="profile.html"><img src="<%= asset_path 'ui-sam.jpg' %>" class="img-circle" width="60"></a></p>
              	  <h5 class="centered">E-node</h5>
              	  	
                  <li class="mt">
                      <a class="active" href="index.html">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-desktop"></i>
                          <span>UI Elements</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="general.html">General</a></li>
                          <li><a  href="buttons.html">Buttons</a></li>
                          <li><a  href="panels.html">Panels</a></li>
                      </ul>
                  </li>

                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-cogs"></i>
                          <span>Components</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="calendar.html">Calendar</a></li>
                          <li><a  href="gallery.html">Gallery</a></li>
                          <li><a  href="todo_list.html">Todo List</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-book"></i>
                          <span>Extra Pages</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="blank.html">Blank Page</a></li>
                          <li><a  href="login.html">Login</a></li>
                          <li><a  href="lock_screen.html">Lock Screen</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-tasks"></i>
                          <span>Forms</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="form_component.html">Form Components</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class="fa fa-th"></i>
                          <span>Data Tables</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="basic_table.html">Basic Table</a></li>
                          <li><a  href="responsive_table.html">Responsive Table</a></li>
                      </ul>
                  </li>
                  <li class="sub-menu">
                      <a href="javascript:;" >
                          <i class=" fa fa-bar-chart-o"></i>
                          <span>Charts</span>
                      </a>
                      <ul class="sub">
                          <li><a  href="morris.html">Morris</a></li>
                          <li><a  href="chartjs.html">Chartjs</a></li>
                      </ul>
                  </li>

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->

app/views/shared/_sidebarCompany.html.erb
    <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">

              	  <p class="centered"><a href="<%= edit_company_registration_path %>"><img src="<%= current_entity.avatar.url %>" class="img-circle" width="100"></a></p>
              	  <h5 class="centered"><%= current_entity.razon %></h5>

                  <li class="mt">
                      <a href="<%= dashboards_company_path %>" >
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="<%= edit_company_registration_path %>" data-no-turbolink= "false" >
                          <i class="fa fa-cogs"></i>
                          <span>Perfil</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="<%= publications_path %>" >
                          <i class="fa fa-desktop"></i>
                          <span>Publicaciones</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="<%= new_publication_path %>" data-no-turbolink= "false" >
                          <i class="fa fa-desktop"></i>
                          <span>Crear Publicacion</span>
                      </a>
                  </li>

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->

app/views/shared/_sidebarUser.html.erb
    <!--sidebar start-->
      <aside>
          <div id="sidebar"  class="nav-collapse ">
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">

              	  <p class="centered"><a href="<%= edit_user_registration_path %>"><img src="<%= current_entity.avatar %>" class="img-circle" width="100"></a></p>
              	  <h5 class="centered"><%= current_entity.nombre %></h5>

                  <li class="mt">
                      <a href="<%= dashboards_student_path %>">
                          <i class="fa fa-dashboard"></i>
                          <span>Dashboard</span>
                      </a>
                  </li>

                  <li class="mt">
                      <a href="<%= edit_user_registration_path %>">
                          <i class="fa fa-dashboard"></i>
                          <span>Perfil</span>
                      </a>
                  </li>

                  <li class="mt">
                      <a href="<%= publications_path %>">
                          <i class="fa fa-dashboard"></i>
                          <span>Publicaciones</span>
                      </a>
                  </li>

                  <!-- <li class="mt">
                      <a href="<%=  %>">
                          <i class="fa fa-dashboard"></i>
                          <span>Postulaciones</span>
                      </a>
                  </li> -->

              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->